### ISSUE TITLE
Build Error on WebGL 2021.3.4f1

### ISSUE THREAD

**Issue by afzaale01** [livekit/client-sdk-unity-web#21]
Facing this error in webgl build. Please check the logs and error image
[BuildLogLivekitEditor.log](https://github.com/livekit/client-sdk-unity-web/files/9695824/BuildLogLivekitEditor.log)
![builderror](https://user-images.githubusercontent.com/60592691/193533162-cc84f457-a13d-4470-9a78-80aa1347bd23.png)

**Comment by theomonnom** [comment]
Hey, this issue seems unrelated to LiveKit. Can you provide more details about how to reproduce this?
The SDK doesn't use `System.Net.WebHeaderCollection/RfcChar`
