### ISSUE TITLE
Unity editor can not run, packaged out WebGL can run. Is this my configuration problem?

### ISSUE THREAD

**Issue by xiejunsheng03** [livekit/client-sdk-unity-web#37]

**Comment by davidzhao** [comment]
This is a known issue. This will be resolved once we merge the unity-web SDK back into client-sdk-unity

**Comment by lifeoasis-chudee** [comment]
how to merge?

**Comment by lifeoasis-chudee** [comment]
As you know, webgl build takes a long time, so I try to develop with unity editor and build the result with webgl, but I get an error in JSNative.NewRef().
